# -*- coding: utf-8 -*-
"""Project1(AP).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qzv4nQk9gVeSRmhNIth7hJnc42i3NaJB

# Βιβλιοθήκες
"""

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from collections import Counter
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestCentroid

"""# Φόρτωση Δεδομένων

"""

print('Φόρτωση δεδομένων MNIST')

#κατεβάζουμε το dataset
#mnist_784: το όνομα της βάσης
#as_frame=False: επιστρέφει τα δεδομένα σε μορφή πιμνάκων Numpy
mnist = fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')

#X: περιέχει τις εικόνες (784 pixels για κάθε εικόνα)
#y: περιέχει τις ετικέτες (τον πραγματικό αριθμό που δείχνει η εικόνα)
X=mnist.data
y=mnist.target

print("Η λήψη ολοκληρώθηκε")
print("Διαστάσεις δεδομένων (εικόνες, pixels):", X.shape)
print("Διαστάσεις των ετικετών:", y.shape)

"""# Προεπεξεργασία και Διαχωρισμός Δεδομένων"""

#κανονικοποίηση
X=X/255.0

#διαχωρισμός (train split - test split)
#train_size=10000: κρατάμε 10000 εικόνες για εκπαίδευση
#test_size=2000: κρατάμε 2000 εικόνες για εξέταση
#random_state=42: τυχαιότητα
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=60000, test_size=10000, random_state=42)

"""# **K-nn classifier - Κ πλησιέστεροι γείτονες**

Αποθηκεύει ολόκληρο το σύνολο εκπαίδευσης στην μνήμη τυ. Όταν έρχεται μία άγνωστη εικόνα, μετράει την απόστασή της από όλες τις 10.000 γνωστές εικόνες. Βρίσκει τις k πιο κοντινές και κάνει ψηφοφορία.

---
Έτοιμη υλοποίηση για επαλήθευση

---
"""

knn_model=KNeighborsClassifier(n_neighbors=3, metric='euclidean') #δημιουργία μοντέλου, ξεκινάω με k=3, υπολογίζω ευκλείδια απόσταση
knn_model.fit(X_train,y_train) #εκπαίδευση
y_predict_knn=knn_model.predict(X_test) #πρόβλεψη
rating=accuracy_score(y_test,y_predict_knn) #αξιολόγηση
print(f"Αξιολόγηση: {rating}")

"""---
Δική μου υλοποίηση

---




"""

k=3
y_predict_knn=[] #λίστα προβλέψεων

for x in X_test: #για κάθε εικόνα
  distances=np.sqrt(np.sum((X_train-x)**2, axis=1)) #Ευκλείδεια απόσταση του x από κάθε γραμμή του X_train (δηλαδή από όλα)
  indices=np.argsort(distances)[:k] #κρατάμε μόνο τους k κοντινότερους
  k_nearest_labels=y_train[indices]
  most_common=Counter(k_nearest_labels).most_common(1)[0][0] #ποια ετικέτα εμφανίζεται πιο συχνά
  y_predict_knn.append(most_common)

#αξιολόγηση
rating=accuracy_score(y_test,y_predict_knn)
print(f"Αξιολόγηση: {rating}")

"""---
Παραδείγματα ορθής ταξινόμησης

---



"""

#y_predict_knn: οι δικές μου προβλέψεις
#y_test: οι πραγματικές ετικέτες
#θέλουμε y_predict_knn==y_test

y_predict_knn_array=np.array(y_predict_knn) #μετατροπή λίστας σε πίνακα για ευκολία
correct=np.where(y_predict_knn_array==y_test)[0] #θέσεις που είναι ίδια, δηλαδή η πρόβλεψη είναι σωστή

figure,axes=plt.subplots(2,3,figsize=(9,6)) #οι 6 εικόνες θα εμφανιστούν σε 2 γραμμές και 3 στήλες
axes=axes.flatten()

for i in range(6): #για 6 σωστές προβλέψεις
  index=correct[i]
  image=X_test[index].reshape(28,28) #μετατρέπω το διάνυσμα 784 θέσεων, σε εικόνα 28x28

  #εμφάνιση εικόνων
  ax=axes[i]
  ax.imshow(image, cmap='gray')
  ax.set_title(f"Πρόβλεψη: {y_predict_knn_array[index]} \n Πραγματικό: {y_test[index]}")
  ax.axis('off')

#εμφάνιση
plt.tight_layout()
plt.savefig("correct_knn.png", bbox_inches='tight', dpi=300)
plt.show()

"""---
Παραδείγματα εσφαλμένης ταξινόμησης

---
"""

#y_predict_knn: οι δικές μου προβλέψεις
#y_test: οι πραγματικές ετικέτες
#θέλουμε y_predict_knn!=y_test

y_predict_knn_array=np.array(y_predict_knn) #μετατροπή λίστας σε πίνακα για ευκολία
incorrect=np.where(y_predict_knn_array!=y_test)[0] #θέσεις που είναι διαφορετικά, δηλαδή η πρόβλεψη είναι λάθος

figure,axes=plt.subplots(2,3,figsize=(9,6)) #οι 6 εικόνες θα εμφανιστούν σε 2 γραμμές και 3 στήλες
axes=axes.flatten()

for i in range(6): #για 6 λάθος προβλέψεις
  index=incorrect[i]
  image=X_test[index].reshape(28,28) #μετατρέπω το διάνυσμα 784 θέσεων, σε εικόνα 28x28

  #εμφάνιση εικόνων
  ax=axes[i]
  ax.imshow(image, cmap='gray')
  ax.set_title(f"Πρόβλεψη: {y_predict_knn_array[index]} \n Πραγματικό: {y_test[index]}")
  ax.axis('off')

#εμφάνιση και αποθήκευση εικόνας
plt.tight_layout()
plt.savefig("incorrect_knn.png", bbox_inches='tight', dpi=300)
plt.show()

"""---
Πίνακες σύγχυσης

---



"""

#k=3, k=100, k=2500, k=9000, k=34500, k=60000, Ευκλείδεια απόσταση
#λίστες προβλέψεων
y_predict_knn_k3=[] #k=3
y_predict_knn_k100=[] #k=100
y_predict_knn_k2500=[] #k2500
y_predict_knn_k9000=[] #k=9000
y_predict_knn_k34500=[] #k=34500
y_predict_knn_k60000=[] #k=60000

for x in X_test: #για κάθε εικόνα
  distances=np.sqrt(np.sum((X_train-x)**2, axis=1)) #Ευκλείδεια απόσταση του x από κάθε γραμμή του X_train (δηλαδή από όλα)
  indices=np.argsort(distances) #ταξινόμηση

  k3_nearest_labels=y_train[indices[:3]] #k=3
  k100_nearest_labels=y_train[indices[:100]] #k=100
  k2500_nearest_labels=y_train[indices[:2500]] #k=2500
  k9000_nearest_labels=y_train[indices[:9000]] #k=9000
  k34500_nearest_labels=y_train[indices[:34500]] #k=34500
  k60000_nearest_labels=y_train[indices[:60000]] #k=60000

  #ποια ετικέτα εμφανίζεται πιο συχνά
  most_common_k3=Counter(k3_nearest_labels).most_common(1)[0][0] #k=3
  most_common_k100=Counter(k100_nearest_labels).most_common(1)[0][0] #k=100
  most_common_k2500=Counter(k2500_nearest_labels).most_common(1)[0][0] #k=2500
  most_common_k9000=Counter(k9000_nearest_labels).most_common(1)[0][0] #k=9000
  most_common_k34500=Counter(k34500_nearest_labels).most_common(1)[0][0] #k=34500
  most_common_k60000=Counter(k60000_nearest_labels).most_common(1)[0][0] #k=60000

  y_predict_knn_k3.append(most_common_k3) #k=3
  y_predict_knn_k100.append(most_common_k100) #k=100
  y_predict_knn_k2500.append(most_common_k2500) #k=2500
  y_predict_knn_k9000.append(most_common_k9000) #k=9000
  y_predict_knn_k34500.append(most_common_k34500) #k=34500
  y_predict_knn_k60000.append(most_common_k60000) #k=60000

#αξιολόγηση
rating_k3=accuracy_score(y_test,y_predict_knn_k3) #k=3
rating_k100=accuracy_score(y_test,y_predict_knn_k100) #k=100
rating_k2500=accuracy_score(y_test,y_predict_knn_k2500) #k=2500
rating_k9000=accuracy_score(y_test,y_predict_knn_k9000) #k=9000
rating_k34500=accuracy_score(y_test,y_predict_knn_k34500) #k=34500
rating_k60000=accuracy_score(y_test,y_predict_knn_k60000) #k=60000

print(f"Αξιολόγηση για k=3: {rating_k3}")
print(f"Αξιολόγηση για k=100: {rating_k100}")
print(f"Αξιολόγηση για k=2500: {rating_k2500}")
print(f"Αξιολόγηση για k=9000: {rating_k9000}")
print(f"Αιξιολόγηση για k=34500: {rating_k34500}")
print(f"Αξιολόγηση για k=60000: {rating_k60000}")

#πίνακες σύγχυσης για Ευκλείδεια απόσταση
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

#λίστες προβλέψεων
cm_eucl_k3=confusion_matrix(y_test, y_predict_knn_k3) #k=3
cm_eucl_k100=confusion_matrix(y_test, y_predict_knn_k100) #k=100
cm_eucl_k2500=confusion_matrix(y_test, y_predict_knn_k2500) #k=2500
cm_eucl_k9000=confusion_matrix(y_test, y_predict_knn_k9000) #k=9000
cm_eucl_k34500=confusion_matrix(y_test, y_predict_knn_k34500) #k=34500
cm_eucl_k60000=confusion_matrix(y_test, y_predict_knn_k60000) #k=60000

figure,axes=plt.subplots(3,2,figsize=(12,15)) #3 γραμμές, 2 στήλες

eucl_k3=ConfusionMatrixDisplay(confusion_matrix=cm_eucl_k3) #k=3
eucl_k100=ConfusionMatrixDisplay(confusion_matrix=cm_eucl_k100) #k=100
eucl_k2500=ConfusionMatrixDisplay(confusion_matrix=cm_eucl_k2500) #k=2500
eucl_k9000=ConfusionMatrixDisplay(confusion_matrix=cm_eucl_k9000) #k=9000
eucl_k34500=ConfusionMatrixDisplay(confusion_matrix=cm_eucl_k34500) #k=34500
eucl_k60000=ConfusionMatrixDisplay(confusion_matrix=cm_eucl_k60000) #k=60000

eucl_k3.plot(cmap='Blues', ax=axes[0,0], values_format='d')
axes[0,0].set_title("k=3, Ευκλείδεια")
eucl_k100.plot(cmap='Blues', ax=axes[0,1], values_format='d')
axes[0,1].set_title("k=100, Ευκλείδεια")
eucl_k2500.plot(cmap='Blues', ax=axes[1,0], values_format='d')
axes[1,0].set_title("k=2500, Ευκλείδεια")
eucl_k9000.plot(cmap='Blues', ax=axes[1,1], values_format='d')
axes[1,1].set_title("k=9000, Ευκλείδεια")
eucl_k34500.plot(cmap='Blues', ax=axes[2,0], values_format='d')
axes[2,0].set_title("k=34500, Ευκλείδεια")
eucl_k60000.plot(cmap='Blues', ax=axes[2,1], values_format='d')
axes[2,1].set_title("k=60000, Ευκλιδεια")

plt.tight_layout()
plt.savefig("matrix_euclidean.png", bbox_inches='tight', dpi=300)
plt.show()

#k=3, k=100, k=2500, k=9000, k=34500, k=60000, απόσταση Manhattan
#λίστες προβλέψεων
y_predict_knn_k3=[] #k=3
y_predict_knn_k100=[] #k=100
y_predict_knn_k2500=[] #k=2500
y_predict_knn_k9000=[] #k=9000
y_predict_knn_k34500=[] #k=34500
y_predict_knn_k60000=[] #k=60000

for x in X_test: #για κάθε εικόνα
  distances = np.sum(np.abs(X_train - x), axis=1) #απόσταση Manhattan του x από κάθε γραμμή του X_train (δηλαδή από όλα)
  indices=np.argsort(distances) #ταξινόμηση

  k3_nearest_labels=y_train[indices[:3]] #k=3
  k100_nearest_labels=y_train[indices[:100]] #k=100
  k2500_nearest_labels=y_train[indices[:2500]] #k=2500
  k9000_nearest_labels=y_train[indices[:9000]] #k=9000
  k34500_nearest_labels=y_train[indices[:34500]] #k=34500
  k60000_nearest_labels=y_train[indices[:60000]] #k=60000

  #ποια ετικέτα εμφανίζεται πιο συχνά
  most_common_k3=Counter(k3_nearest_labels).most_common(1)[0][0] #k=3
  most_common_k100=Counter(k100_nearest_labels).most_common(1)[0][0] #k=100
  most_common_k2500=Counter(k2500_nearest_labels).most_common(1)[0][0] #k=2500
  most_common_k9000=Counter(k9000_nearest_labels).most_common(1)[0][0] #k=9000
  most_common_k34500=Counter(k34500_nearest_labels).most_common(1)[0][0] #k=34500
  most_common_k60000=Counter(k60000_nearest_labels).most_common(1)[0][0] #k=60000

  y_predict_knn_k3.append(most_common_k3) #k=3
  y_predict_knn_k100.append(most_common_k100) #k=100
  y_predict_knn_k2500.append(most_common_k2500) #k=2500
  y_predict_knn_k9000.append(most_common_k9000) #k=9000
  y_predict_knn_k34500.append(most_common_k34500) #k=34500
  y_predict_knn_k60000.append(most_common_k60000) #k=60000

#αξιολόγηση
rating_k3=accuracy_score(y_test,y_predict_knn_k3) #k=3
rating_k100=accuracy_score(y_test,y_predict_knn_k100) #k=100
rating_k2500=accuracy_score(y_test,y_predict_knn_k2500) #k=2500
rating_k9000=accuracy_score(y_test,y_predict_knn_k9000) #k=9000
rating_k34500=accuracy_score(y_test,y_predict_knn_k34500) #k=34500
rating_k60000=accuracy_score(y_test,y_predict_knn_k60000) #k=60000

print(f"Αξιολόγηση για k=3: {rating_k3}")
print(f"Αξιολόγηση για k=100: {rating_k100}")
print(f"Αξιολόγηση για k=2500: {rating_k2500}")
print(f"Αξιολόγηση για k=9000: {rating_k9000}")
print(f"Αξιολόγηση για k=34500: {rating_k34500}")
print(f"Αξιολόγηση για k=60000: {rating_k60000}")

#πίνακες σύγχυσης για απόσταση Manhattan
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

#λίστες προβλέψεων
cm_man_k3=confusion_matrix(y_test, y_predict_knn_k3) #k=3
cm_man_k100=confusion_matrix(y_test, y_predict_knn_k100) #k=100
cm_man_k2500=confusion_matrix(y_test, y_predict_knn_k2500) #k=2500
cm_man_k9000=confusion_matrix(y_test, y_predict_knn_k9000) #k=9000
cm_man_k34500=confusion_matrix(y_test, y_predict_knn_k34500) #k=34500
cm_man_k60000=confusion_matrix(y_test, y_predict_knn_k60000) #k=60000

figure,axes=plt.subplots(3,2,figsize=(12,15)) #3 γραμμές, 2 στήλες

man_k3=ConfusionMatrixDisplay(confusion_matrix=cm_man_k3) #k=3
man_k100=ConfusionMatrixDisplay(confusion_matrix=cm_man_k100) #k=100
man_k2500=ConfusionMatrixDisplay(confusion_matrix=cm_man_k2500) #k=2500
man_k9000=ConfusionMatrixDisplay(confusion_matrix=cm_man_k9000) #k=9000
man_k34500=ConfusionMatrixDisplay(confusion_matrix=cm_man_k34500) #k=34500
man_k60000=ConfusionMatrixDisplay(confusion_matrix=cm_man_k60000) #k=60000

man_k3.plot(cmap='Greens', ax=axes[0,0], values_format='d')
axes[0,0].set_title("k=3, Manhattan")
man_k100.plot(cmap='Greens', ax=axes[0,1], values_format='d')
axes[0,1].set_title("k=100, Manhattan")
man_k2500.plot(cmap='Greens', ax=axes[1,0], values_format='d')
axes[1,0].set_title("k=2500, Manhattan")
man_k9000.plot(cmap='Greens', ax=axes[1,1], values_format='d')
axes[1,1].set_title("k=9000, Manhattan")
man_k34500.plot(cmap='Greens', ax=axes[2,0], values_format='d')
axes[2,0].set_title("k=34500, Manhattan")
man_k60000.plot(cmap='Greens', ax=axes[2,1], values_format='d')
axes[2,1].set_title("k=60000, Manhattan")

plt.tight_layout()
plt.savefig("matrix_manhattan.png", bbox_inches='tight', dpi=300)
plt.show()

"""# **Nearest Centroid Classifier - Πλησιέστερα κέντρα**

Ο αλγόριθμος παίρνει όλες τις εικόνες του κάθε ψηφίου ξεχωριστά και βρίσκει τον μέσο όρο τους (το κέντρο τους). Όταν του δώσουμε μία νέα, άγνωστη εικόνα από το X_test, μετράει την απόστασή της από αυτά τα 10 κέντρα και την ταξινομεί σε αυτό που είναι πιο κοντά

---
Έτοιμη υλοποίηση για επαλήθευση

---
"""

nc_model=NearestCentroid() #δημιουργία μοντέλου
nc_model.fit(X_train,y_train) #εκπαίδευση
y_predict_nc=nc_model.predict(X_test) #πρόβλεψη
rating=accuracy_score(y_test,y_predict_nc) #αξιολόγηση
print(f"Αξιολόγηση: {rating}")

"""---
Δική μου υλοποίηση

---

"""

centroids={} #εδώ αποθηκεύουμε τα 10 κέντρα

for c in np.unique(y_train): #για κάθε κλάση
  class_images=X_train[y_train==c] #εικόνες με ετικέτα c
  centroids[c]=np.mean(class_images, axis=0) #μέσος όρος

#εύρεση πλησιέστερου κέντρου
y_predict_nc=[] #λίστα που αποθηκεύει τις προβλέψεις
for x in X_test: #για κάθε εικόνα
  distances=[] #λίστα με τις απόστασεις της εικόνας x από κάθε κέντρο
  for c in centroids: #για κάθε κέντρο
    dist=np.sqrt(np.sum((x-centroids[c])**2)) #Ευκλείδεια απόσταση μεταξύ εικόνας και κέντρου
    distances.append((dist,c)) #προσθέτω απόσταση και κέντρο
  best_dist, best_class=min(distances) #κρατάω την μικρότερη απόσταση και την κλάση της
  y_predict_nc.append(best_class)

#αξιολόγηση
rating=accuracy_score(y_test,y_predict_nc)
print(f"Αξιολόγηση: {rating}")

"""---
Παραδείγματα ορθής ταξινόμησης

---
"""

#y_predict_nc: οι δικές μου προβλέψεις
#y_test: οι πραγματικές ετικέτες
#θέλουμε y_predict_nc==y_test

y_predict_nc_array=np.array(y_predict_nc) #μετατροπή λίστας σε πίνακα για ευκολία
correct=np.where(y_predict_nc_array==y_test)[0] #θέσεις που είναι ίδια, δηλαδή η πρόβλεψη είναι σωστή

figure,axes=plt.subplots(2,3,figsize=(9,6)) #οι 6 εικόνες θα εμφανιστούν σε 2 γραμμές και 3 στήλες
axes=axes.flatten()

for i in range(6): #για 6 σωστές προβλέψεις
  index=correct[i]
  image=X_test[index].reshape(28,28) #μετατρέπω το διάνυσμα 784 θέσεων, σε εικόνα 28x28

  #εμφάνιση εικόνων
  ax=axes[i]
  ax.imshow(image, cmap='gray')
  ax.set_title(f"Πρόβλεψη: {y_predict_nc_array[index]} \n Πραγματικό: {y_test[index]}")
  ax.axis('off')

#εμφάνιση
plt.tight_layout()
plt.savefig("correct_nc.png", bbox_inches='tight', dpi=300)
plt.show()

"""---
Παραδείγματα εσφαλμένης ταξινόμησης

------
"""

#y_predict_nc: οι δικές μου προβλέψεις
#y_test: οι πραγματικές ετικέτες
#θέλουμε y_predict_nc!=y_test

y_predict_nc_array=np.array(y_predict_nc) #μετατροπή λίστας σε πίνακα για ευκολία
incorrect=np.where(y_predict_nc_array!=y_test)[0] #θέσεις που είναι διαφορετικά, δηλαδή η πρόβλεψη είναι λάθος

figure,axes=plt.subplots(2,3,figsize=(9,6)) #οι 6 εικόνες θα εμφανιστούν σε 2 γραμμές και 3 στήλες
axes=axes.flatten()

for i in range(6): #για 6 λάθος προβλέψεις
  index=incorrect[i]
  image=X_test[index].reshape(28,28) #μετατρέπω το διάνυσμα 784 θέσεων, σε εικόνα 28x28

  #εμφάνιση εικόνων
  ax=axes[i]
  ax.imshow(image, cmap='gray')
  ax.set_title(f"Πρόβλεψη: {y_predict_nc_array[index]} \n Πραγματικό: {y_test[index]}")
  ax.axis('off')

#εμφάνιση
plt.tight_layout()
plt.savefig("incorrect_nc.png", bbox_inches='tight', dpi=300)
plt.show()

"""---
Πίνακες σύγχυσης


---



"""

centroids={} #εδώ αποθηκεύουμε τα 10 κέντρα

for c in np.unique(y_train): #για κάθε κλάση
  class_images=X_train[y_train==c] #εικόνες με ετικέτα c
  centroids[c]=np.mean(class_images, axis=0) #μέσος όρος

#εύρεση πλησιέστερου κέντρου
#λίστες για τις προβλέψεις
y_predict_eucl_nc=[] #Ευκλείδεια απόσταση
y_predict_man_nc=[] #απόσταση Manhattan
for x in X_test: #για κάθε εικόνα

  #λίστες με τις απόστασεις της εικόνας x από κάθε κέντρο
  distances_eucl=[] #Ευκλείδεια απόσταση
  distances_man=[] #απόσταση Manhattan

  for c in centroids: #για κάθε κέντρο
    dist_eucl=np.sqrt(np.sum((x-centroids[c])**2)) #Ευκλείδεια απόσταση μεταξύ εικόνας και κέντρου
    dist_man=np.sum(np.abs(x-centroids[c])) #απόσταση Manhattan μεταξύ εικόνας και κέντρου

    #πορσθέτω απόσταση και κέντρο
    distances_eucl.append((dist_eucl,c)) #Ευκλείδεια απόσταση
    distances_man.append((dist_man,c)) #απόσταση Manhattan

  #κρατάω την μικρότερη απόσταση και την κλάση της
  best_dist_eucl, best_class_eucl=min(distances_eucl) #Ευκλείδεια απόσταση
  y_predict_eucl_nc.append(best_class_eucl)
  best_dist_man, best_class_man=min(distances_man) #απόσταση Manhattan
  y_predict_man_nc.append(best_class_man)

#αξιολόγηση
rating_eucl=accuracy_score(y_test,y_predict_eucl_nc)
rating_man=accuracy_score(y_test,y_predict_man_nc)
print(f"Αξιολόγηση Ευκλείδειας απόστασης: {rating_eucl}")
print(f"Αξιολόγηση απόστασης Manhattan: {rating_man}")

#πίνακες σύγχυσης
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

#λίστες προβλέψεων
cm_eucl=confusion_matrix(y_test, y_predict_eucl_nc) #Ευκλείδεια
cm_man=confusion_matrix(y_test, y_predict_man_nc) #Manhattan

figure,axes=plt.subplots(2,1,figsize=(6,8)) #2 γραμμές, 1 στήλη

eucl=ConfusionMatrixDisplay(confusion_matrix=cm_eucl) #Ευκλείδεια
man=ConfusionMatrixDisplay(confusion_matrix=cm_man) #Manhattan

eucl.plot(cmap='Blues', ax=axes[0], values_format='d')
axes[0].set_title("Ευκλείδεια")
man.plot(cmap='Greens', ax=axes[1], values_format='d')
axes[1].set_title("Manhattan")

plt.tight_layout()
plt.savefig("matrix_nc.png", bbox_inches='tight', dpi=300)
plt.show()